const CHARACTERS = [
    {
        name: 'Harry Potter',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Male',
        house: 'Gryffindor',
        dateOfBirth: '31-07-1980',
        yearOfBirth: 1980,
        wizard: true,
        ancentry: 'Half-blood',
        eyeColour: 'Green',
        hairColour: 'Black',
        wand: 'Wood : holly, core : phoenix feather, length : 11',
        patronus: 'Stag',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: 'Daniel Radcliff',
        alive: true,
        img: '/img/Potter.jpg',
    },

    {
        name: 'Hermione Granger',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Female',
        house: 'Gryffindor',
        dateOfBirth: '19-09-1979',
        yearOfBirth: 1979,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: '',
        alive: true,
        img: '/img/Granger.jpg',
    },
    {
        name: 'Ron Weasley',
        alternateNames: 'Dragomir Despard',
        species: 'Human',
        gend: 'Male',
        house: 'Gryffindor',
        dateOfBirth: '01-03-1980',
        yearOfBirth: 1980,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: '',
        alive: true,
        img: '/img/Weasley.jpg',
    },
    {
        name: 'Draco Malfoy',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Male',
        house: 'Slytherin',
        dateOfBirth: '05-06-1980',
        yearOfBirth: 1980,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: '',
        alive: true,
        img: '/img/Malfoy.jpg',
    },
    {
        name: 'Cedric Diggory',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Male',
        house: 'Hufflepuff',
        dateOfBirth: '31-07-1980',
        yearOfBirth: 1980,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: '',
        alive: true,
        img: '/img/Diggory.jpg',
    },
    {
     name: 'Cho Chang',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Female',
        house: 'Ravenclaw',
        dateOfBirth: '07-04-1979',
        yearOfBirth: 1979,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: '',
        alive: true,
        img: '/img/Chan.jpg',
    },
    {
      name: 'Neville Longbottom',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Male',
        house: 'Gryffindor',
        dateOfBirth: '30-07-1980',
        yearOfBirth: 1980,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: '',
        alive: true,
        img: '/img/Longbottom.jpg',
    },
    {
        name: 'Luna Lovegood',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Female',
        house: 'Ravenclaw',
        dateOfBirth: '13-02-1981',
        yearOfBirth: 1981,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: true,
        hogwartsStaff: false,
        actor: '',
        alive: true,
        img: '/img/Lovegood.jpg',
    },
   {
        name: 'Minerva McGonagall',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Female',
        house: 'Gryffindor',
        dateOfBirth: '4-10-1925',
        yearOfBirth: 1925,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Minerva.jpg',
    },
      {
        name: 'Severus Snape',
        alternateNames: 'Half-Blood Princ',
        species: 'Human',
        gend: 'Male',
        house: 'Slytherin',
        dateOfBirth: '09-01-1960',
        yearOfBirth: 1960,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Snape.jpg',
    },
         {
        name: 'Rubeus Hagrid',
        alternateNames: 'Dragonmir Despard',
        species: 'Human',
        gend: 'Male',
        house: 'Gryffindor',
        dateOfBirth: '06-12-1928',
        yearOfBirth: 1928,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Hagrid.jpg',
    },
            {
        name: 'Remus Lupin',
        alternateNames: 'Professor Lupin, Moony',
        species: 'Human',
        gend: 'Male',
        house: 'Gryffindor',
        dateOfBirth: '10-03-1960',
        yearOfBirth: 1960,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Lupin.jpg',
    },
     {
        name: 'Horace Slughorm',
        alternateNames: 'The Boy Why Lived',
        species: 'Human',
        gend: 'Male',
        house: 'Slytherin',
        dateOfBirth: null,
        yearOfBirth: null,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Slughorn.jpg',
    },
    {
        name: 'Dolores Umbridge',
        alternateNames: 'The Boy Why Lived',
        species: 'Human',
        gend: 'Female',
        house: 'Slytherin',
        dateOfBirth: null,
        yearOfBirth: null,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Umbridge.jpg',
    },
    {
        name: 'Argus Filch',
        alternateNames: 'The Boy Who Lived',
        species: 'Human',
        gend: 'Male',
        house: 'Gryffindor',
        dateOfBirth: null,
        yearOfBirth: null,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Filch.jpg',
    },
    {
        name: 'Albus Dumbledore',
        alternateNames: 'Professor Dumbledor',
        species: 'Human',
        gend: 'Male',
        house: 'Gryffindor',
        dateOfBirth: null,
        yearOfBirth: null,
        wizard: true,
        ancentry: '',
        eyeColour: '',
        hairColour: '',
        wand: '',
        patronus: '',
        hogwartsStudent: false,
        hogwartsStaff: true,
        actor: '',
        alive: true,
        img: '/img/Dumbledore.jpg',
    },
];